# Generated by Django 3.2.16 on 2024-11-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество')),
                ('organization', models.CharField(max_length=30, verbose_name='Организация')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('email', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Эл. почта')),
            ],
            options={
                'verbose_name': 'заказчик',
                'verbose_name_plural': 'заказчики',
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoldOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='№ заказа')),
                ('gold_amount', models.IntegerField(verbose_name='Количество золота')),
                ('ordering_date', models.DateField(verbose_name='Срок оформления заказа')),
                ('deadline', models.DateField(verbose_name='Срок сдачи заказа')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'db_table': 'gold_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'статус',
                'verbose_name_plural': 'статусы',
                'db_table': 'order_states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Звание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'звание',
                'verbose_name_plural': 'звания',
                'db_table': 'position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Задача')),
                ('completed', models.BooleanField(verbose_name='Выполнен')),
                ('step', models.IntegerField(verbose_name='Шаг')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'db_table': 'tasks',
                'managed': False,
            },
        ),
    ]
